/*
 *
 */

package util.update;

/**
 *
 * @author  Martin Pröhl alias MythGraphics
 * @version 1.0.4
 *
 */

import java.io.IOException;

public class UpdateFrame extends javax.swing.JFrame {

    private final Update update;

    public static void main(String args[]) throws IOException {
        Runnable r;
        if (args.length >= 2) {
            r = () ->
            {
                try { new UpdateFrame( args[0], args[1] ).setVisible(true); }
                catch (IOException e) { e.printStackTrace(); }
            };
        } else {
            r = () ->
            {
                try { new UpdateFrame(null).setVisible(true); }
                catch (IOException e) { e.printStackTrace(); }
            };
        }
        java.awt.EventQueue.invokeLater(r);
    }

    public UpdateFrame(String name, String version) throws IOException {
        update = new Update( name, version );
        initComponents();
    }

    public UpdateFrame(Update update) throws IOException {
        this.update = update;
        initComponents();
        if (update == null) {
            jButton1.setEnabled(false);
            jTextField1.show( "keine Daten", jTextField1.ERROR );
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jTextField1 = new gui.JAdvTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Update");
        setLocation(new java.awt.Point(0, 0));
        setName("UpdateFrame"); // NOI18N
        setResizable(false);
        setType(java.awt.Window.Type.UTILITY);

        jButton1.setText("Nach Update suchen");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Update herunterladen");
        jButton2.setEnabled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jTextField1.setEditable(false);
        jTextField1.setHorizontalAlignment(0);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(11, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jButton1)
                .addGap(7, 7, 7)
                .addComponent(jButton2)
                .addGap(27, 27, 27)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        update.download();
        jTextField1.show(
            "Update erfolgreich heruntergeladen. ", jTextField1.SUCCESS
        );
        jButton2.setEnabled(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if ( update.isAvailable() ) {
            jTextField1.show( "Update verfügbar !", jTextField1.SUCCESS );
            jButton2.setEnabled(true);
        } else {
            jTextField1.show( "Kein Update verfügbar.", jTextField1.MESSAGE );
            jButton2.setEnabled(false);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void throwException(Exception e) {
        e.printStackTrace();
        jTextField1.show( e.toString(), jTextField1.ERROR );
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private gui.JAdvTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
