/*
 * CalendarApp.java
 *
 * Created on 06.01.2019, 20:04:27
 */

package tools;

/**
 *
 * @author  Martin Pröhl alias MythGraphics
 * @version 2.0.0
 *
 */

import java.text.DateFormat;
import java.util.StringTokenizer;
import java.util.GregorianCalendar;

public class CalendarApp extends javax.swing.JFrame {

    public final static String NAME    = "MythGraphics CalendarApp";
    public final static String VERSION = "2.0.0";
    public final static String[] DAYS  = {
        "Sonntag", "Montag", "Dienstag", "Mittwoch", "Donnerstag", "Freitag", "Samstag"
    };

    private final GregorianCalendar c = new GregorianCalendar();
    private final DateFormat df = DateFormat.getDateInstance( DateFormat.MEDIUM );
    private final String today = df.format( c.getTime() );

    /** Creates new form MainFrame */
    public CalendarApp() {
        initComponents();
        jTextField1.setText(today);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle(NAME + " v" + VERSION);

        jLabel1.setText("Datum:");

        jButton1.setText("Wochentag");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField1)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        jButton1.setText( getDayOfWeek( jTextField1.getText() ));
    }//GEN-LAST:event_jButton1ActionPerformed

    public static String getDayOfWeek(String date) {
        StringTokenizer t = new StringTokenizer( date, ".,/- ", false );
        int day = Integer.parseInt( t.nextToken() );
        int month = Integer.parseInt( t.nextToken() );
        int year = Integer.parseInt( t.nextToken() );
        GregorianCalendar cal = new GregorianCalendar( year, month-1, day);
        String dayOfWeek = DAYS[ cal.get(GregorianCalendar.DAY_OF_WEEK) - 1 ];                      // Sonntag = 1
        return dayOfWeek;
    }

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        if ( (args == null || args.length == 0) || args[0].equalsIgnoreCase("--gui") )
        {
            startGUI();
        }
        else if ( args[0].equalsIgnoreCase("--help") )
        {
            printHelp();
        }
        else if ( args[0].equalsIgnoreCase("--version") )
        {
            System.out.println(NAME + " v" + VERSION);
        }
        else if ( args.length >= 1 )
        {
            for (int i = 0; i < args.length; ++i)
            {
                System.out.println( getDayOfWeek( args[i] ));
            }
        }
        else
        {
            System.err.println("Parameter \"" + args[0] + "\" unbekannt");
            printHelp();
        }

    }

    private static void startGUI() {
        java.awt.EventQueue.invokeLater( new Runnable() {
            @Override
            public void run() {
                new CalendarApp().setVisible(true);
            }
        });
    }

    private static void printHelp() {
        System.out.println("Gibt den Wochentag des gegebenen Datums aus");
        System.out.println();
        System.out.println("Aufruf:");
        System.out.println("[program] dd.mm.yyyy");
        System.out.println();
        System.out.println("Parameter:");
        System.out.println("  --gui         lädt das grafische Interface");
        System.out.println("  --help        zeigt diese Hilfe an");
        System.out.println("  --version     zeigt Programm-Version an");
        System.out.println();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

}
