/*
 * ReNamer.java
 *
 * Created on 04.03.2019, 18:48:10
 */

package tools;

/**
 *
 * @author  Martin Pröhl alias MythGraphics
 * @version 1.0.1
 *
 */

import java.io.File;
import java.io.IOException;
import util.ColorLibrary;

public class ReNamer extends javax.swing.JFrame {

    public final static String NAME     = "MythGraphics ReNamer";
    public final static String VERSION  = "v1.0.0";

    private File path;
    private String filter;

    /** Creates new form ReNamer */
    public ReNamer() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pathField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        filterField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle(NAME + " " + VERSION);

        pathField1.setText("D:\\VideoDownloadHelper");
        pathField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                pathField1FocusGained(evt);
            }
        });

        jLabel1.setText("Pfad:");

        jLabel2.setText("Lösch-String:");

        filterField1.setText(" -");
        filterField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                filterField1FocusGained(evt);
            }
        });

        jButton1.setText("Einlesen");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Bereinigen");
        jButton2.setEnabled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 474, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(filterField1)
                    .addComponent(pathField1)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(6, 6, 6)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pathField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(filterField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 128, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        init();
        String[] fs;                                                                                // FileStrings
        fs = path.list();
        for (int i = 0; i < fs.length; ++i) {
            if ( fs[i].contains(".") && fs[i].contains(filter) ) {
                jTextArea1.append( fs[i] + "\n");
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        File f;
        File[] files = path.listFiles();
        try { for (int i = 0; i < files.length; ++i) {
            if ( files[i].getName().contains(".") && files[i].getName().contains(filter) ) {
                f = getNewFile( files[i].getCanonicalPath(), filter );
                if (( f != null ) && files[i].renameTo(f) ) {
                    jTextArea1.append( files[i].getName() + "\n > " + f.getName() + " \u221A" + "\n" );
                } else {
                    jTextArea1.append( files[i].getName() + "\n > " + f.getName() + " X" + "\n" );
        }}}}
        catch (IOException e) { jTextArea1.append("\n" + e.getMessage() + "\n" ); }
        jButton2.setEnabled(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void pathField1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pathField1FocusGained
        jButton2.setEnabled(false);
    }//GEN-LAST:event_pathField1FocusGained

    private void filterField1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_filterField1FocusGained
        jButton2.setEnabled(false);
    }//GEN-LAST:event_filterField1FocusGained

    private File getNewFile(String old, String filter) {
        String ending = old.substring( old.lastIndexOf(".") );
        String s = old.substring( 0, old.lastIndexOf(filter) );
        s += ending;
        File f = new File(s);
        if ( f.exists() ) {
            return null;
        } else {
            return f;
        }
    }

    private void init() {
        path = new File( pathField1.getText() );
        if ( !path.exists() || !path.isDirectory() ) {
            pathField1.setBackground( ColorLibrary.LIGHT_RED );
            return;
        }
        pathField1.setBackground( ColorLibrary.LIGHT_GREEN );

        filter = filterField1.getText();
        jTextArea1.setText("");
        jButton2.setEnabled(true);
    }

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater( new Runnable() {
            @Override
            public void run() {
                new ReNamer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField filterField1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField pathField1;
    // End of variables declaration//GEN-END:variables

}
